/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

/**
 *
 * @author Priba
 */
public class FmGlavna extends javax.swing.JFrame {

    /**
     * Creates new form FmGlavna
     */
    public FmGlavna() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jmClan = new javax.swing.JMenu();
        jmiPretragaClana = new javax.swing.JMenuItem();
        jmiUnosClana = new javax.swing.JMenuItem();
        jmProjekcija = new javax.swing.JMenu();
        jmiUnosProjekcije = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmClan.setText("Član");

        jmiPretragaClana.setText("Pretraga Clanova");
        jmiPretragaClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPretragaClanaActionPerformed(evt);
            }
        });
        jmClan.add(jmiPretragaClana);

        jmiUnosClana.setText("Unos člana");
        jmiUnosClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosClanaActionPerformed(evt);
            }
        });
        jmClan.add(jmiUnosClana);

        jMenuBar1.add(jmClan);

        jmProjekcija.setText("Projekcija");

        jmiUnosProjekcije.setText("Unos projekcije");
        jmiUnosProjekcije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosProjekcijeActionPerformed(evt);
            }
        });
        jmProjekcija.add(jmiUnosProjekcije);

        jMenuBar1.add(jmProjekcija);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiPretragaClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPretragaClanaActionPerformed
        // TODO add your handling code here:
        FmPrikazClanova FmPC = new FmPrikazClanova(this, true);
        FmPC.setVisible(true);
    }//GEN-LAST:event_jmiPretragaClanaActionPerformed

    private void jmiUnosClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosClanaActionPerformed
        // TODO add your handling code here:
        FmClan FmC = new FmClan(this, true);
        FmC.setVisible(true);
    }//GEN-LAST:event_jmiUnosClanaActionPerformed

    private void jmiUnosProjekcijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosProjekcijeActionPerformed
        // TODO add your handling code here:
        FmProjekcija fmp = new FmProjekcija(this, true);
        fmp.setVisible(true);
    }//GEN-LAST:event_jmiUnosProjekcijeActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FmGlavna().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmClan;
    private javax.swing.JMenu jmProjekcija;
    private javax.swing.JMenuItem jmiPretragaClana;
    private javax.swing.JMenuItem jmiUnosClana;
    private javax.swing.JMenuItem jmiUnosProjekcije;
    // End of variables declaration//GEN-END:variables
}
